language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

before_install:
  - pip install -U pip

install:
  - pip install -r requirements.txt
  - pip install -r requirements-tests.txt

script:
  - pytest --cache-clear